<?php
$name      = isset($this->formdata['data']['name']) ? $this->formdata['data']['name'] : '';
$email     = isset($this->formdata['data']['email']) ? $this->formdata['data']['email'] : '';
$mobile    = isset($this->formdata['data']['mobile']) ? $this->formdata['data']['mobile'] : '';
$enquiry   = isset($this->formdata['data']['enquiry']) ? $this->formdata['data']['enquiry'] : '';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/ACTIVE.ico" />
<link rel="stylesheet" type="text/css" href="/css/page-format.css"/>
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link rel="stylesheet" type="text/css" href="/css/topnav.css"/>
<link rel="stylesheet" type="text/css" href="/css/subnav-dropdown.css"/>
<link href='http://fonts.googleapis.com/css?family=Loved+by+the+King' rel='stylesheet' type='text/css'>
<!-- <link rel="stylesheet" type="text/css" href="/css/subnav-sidebar.css"/> -->
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>

<script type="text/javascript">

function slideSwitch() {
    var $active = $('#headerImage IMG.active');

    if ( $active.length == 0 ) $active = $('#headerImage IMG:last');

    var $next =  $active.next().length ? $active.next()
        : $('#headerImage IMG:first');

    $active.addClass('last-active');

    $next.css({opacity: 0.0})
        .addClass('active')
        .animate({opacity: 1.0}, 1000, function() {
            $active.removeClass('active last-active');
        });
}

$(function() {
    setInterval( "slideSwitch()", 4000 );
});

</script>

</head>

<body>

<div id="main_wrapper">

<div id="header_wrapper">
    <div id="headerImage">
		<img src="/images/HEADER_1.jpg" alt="active fusion header 1" class="active" />
		<img src="/images/HEADER_2.jpg" alt="active fusion header 2" />
	</div><!-- end id="headerImage" -->
	<div id="header_content">
		<div id="header_top">
			<div id="header_top_left">
				<a href="/"><img src="/images/LOGO.png" alt="active fusion" /></a>
			</div>
			<div id="header_top_right">
				<div id="free_sports">
					<h2><a href="/">Free Sports for Schools >>></a></h2>
				</div>
				<div id="social_icons">
					<a href="/"><img src="/images/HOME_TWITTER.jpg" alt="twitter" /></a>
					<a href="/"><img src="/images/HOME_FACEBOOK.jpg" alt="facebook" /></a>
				</div>
			</div>
		</div>
		<div id="headerBottom">
			<div id="book">
				<a href="/view/contact"><img src="/images/BOOK.png" alt="book now" /></a>
			</div>
		</div>
	</div>
</div>

<div id="nav_wrapper">
	<div id="topnav">
    	<ul id="mainnav">
        	<?=$this->nav?>
    	</ul>
    </div>
</div>

<div id="content_wrapper">
	<div id="text_wrapper_sub">
		<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
			<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        	?>
        	<?php if(count($this->formdata['errors'])): ?>
                <div id="errors">
                    <p><strong><?=count($this->formdata['errors'])?> error<?php if(count($this->formdata['errors']) > 1): ?>s were<?php else: ?> was<?php endif; ?>  encountered in your contact</strong><br />Please correct these errors and submit the form again.</p>
                    <ul>
                        <?php foreach($this->formdata['errors'] as $error): ?>
                            <li><?=$error?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <form method="post" action="/contact/senddetails/" id="contact_form">
            	<div class="form_field"><label for="name" class="form_desc">Name: <span class="required" style="color: #fff;">(required)</span></label><input class="form_content textfield" type="text" name="name" value="<?=$name?>" /></div>
            	<div class="form_field"><label for="email" class="form_desc">Email: <span class="required" style="color: #fff;">(required)</span></label><input class="form_content textfield" type="text" name="email" value="<?=$email?>" /></div>
            	<div class="form_field"><label for="mobile" class="form_desc">Mobile:</label><input class="form_content textfield" type="text" name="mobile" value="<?=$mobile?>" /></div>
               	<div class="form_field"><label for="enquiry" class="form_desc">Message: <span class="required" style="color: #fff;">(required)</span></label><textarea class="form_content textarea" type="text" name="enquiry" id="enquiry" /><?=$enquiry?></textarea></div>
            	<div class="form_base">
            	   <input type="submit" name="submit_button" value="Submit"/>
                </div>
            </form>
    </div>
</div>

<div id="footer_wrapper">
	<p>This is where the address will go along with any other links that need to appear in the footer<br />
Website produced by <a href="http://www.sugarcaneweb.co.uk">www.sugarcaneweb.co.uk</a></p>
</div>

</div>

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>