<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/ACTIVE.ico" />
<link rel="stylesheet" type="text/css" href="/css/page-format.css"/>
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link rel="stylesheet" type="text/css" href="/css/topnav.css"/>
<link rel="stylesheet" type="text/css" href="/css/subnav-dropdown.css"/>
<link href='http://fonts.googleapis.com/css?family=Loved+by+the+King' rel='stylesheet' type='text/css'>
<!-- <link rel="stylesheet" type="text/css" href="/css/subnav-sidebar.css"/> -->
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>

<script type="text/javascript">

function slideSwitch() {
    var $active = $('#headerImage IMG.active');

    if ( $active.length == 0 ) $active = $('#headerImage IMG:last');

    var $next =  $active.next().length ? $active.next()
        : $('#headerImage IMG:first');

    $active.addClass('last-active');

    $next.css({opacity: 0.0})
        .addClass('active')
        .animate({opacity: 1.0}, 1000, function() {
            $active.removeClass('active last-active');
        });
}

$(function() {
    setInterval( "slideSwitch()", 4000 );
});

</script>

</head>

<body>

<div id="main_wrapper">

<div id="header_wrapper">
    <div id="headerImage">
		<img src="/images/HEADER_1.jpg" alt="active fusion header 1" class="active" />
		<img src="/images/HEADER_2.jpg" alt="active fusion header 2" />
		<img src="/images/HEADER_3.jpg" alt="active fusion header 3" />
		<img src="/images/HEADER_4.jpg" alt="active fusion header 4" />
		<img src="/images/HEADER_5.jpg" alt="active fusion header 5" />
	</div><!-- end id="headerImage" -->
	<div id="header_content">
		<div id="header_top">
			<div id="header_top_left">
				<a href="/"><img src="/images/LOGO.png" width="220px" alt="active fusion" /></a>
			</div>
			<div id="header_top_right">
				<div id="free_sports">
					<h2><a href="/">Free Sports for Schools >>></a></h2>
				</div>
				<div id="social_icons">
					<a href="/"><img src="/images/HOME_TWITTER.jpg" alt="twitter" /></a>
					<a href="/"><img src="/images/HOME_FACEBOOK.jpg" alt="facebook" /></a>
				</div>
			</div>
		</div>
		<div id="headerBottom">
			<div id="book">
				<a href="/view/contact"><img src="/images/BOOK.png" height="105px" alt="book now" /></a>
			</div>
		</div>
	</div>
</div>

<div id="nav_wrapper">
	<div id="topnav">
    	<ul id="mainnav">
        	<?=$this->nav?>
    	</ul>
    </div>
</div>

<div id="content_wrapper">
	<div id="content_left">
		<div id="text_wrapper">
		<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
			<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        	?>
			<div id="latest_news">
				<h2><a href="/news">Latest News >>></a></h2>
   			 	<div id="news_items">
    				<?php if(count($this->newsitems)): ?>
                   
        			<?php foreach($this->newsitems as $newsitem): ?>
        			<div id="latest_news_wrapper">
        			<div id="latest_news_thumb">
            		<a href="/news/view/article/<?=$newsitem['news_id']?>"><img height="90px" src="<?=$newsitem['news_image']?>" alt="<?=$newsitem['title']?>" /></a>
            		</div>
          			<h4 style="margin-bottom: 3px;"><a href="/news/view/article/<?=$newsitem['news_id']?>"><?=$newsitem['title']?></a></h4>
           			<p style="margin-bottom: 0px;"><?=$newsitem['preview']?><a href="/news/view/article/<?=$newsitem['news_id']?>"> More…</a></p>
           			<div id="clear"></div>
           			</div>
            		<?php endforeach; ?>
                    
        			<?php else: ?>
            			<p>No news items found</p>
        			<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
    <div id="content_right">
    	<div class="services">
    		<div class="services_left">
    		<h1><a href="/view/schools">For Schools</a></h1>
    		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum orci nec nibh eleifend non tempor enim volutpat. Vestibulum ornare eleifend tellus ut tempor. Suspendisse vel lorem mollis dui ege.</p>
    		</div>
    		<div class="services_left_image">
    		<a href="/view/schools"><img src="/images/SERVICES_FOR_SCHOOLS.png" alt="for schools" /></a>
    		</div>
    	</div>
    	<div class="services">
    		<div class="services_right_image">
    		<a href="/view/health"><img src="/images/SERVICES_SPORT.png" alt="sport and health" /></a>
    		</div>
    		<div class="services_right">
    		<h1><a href="/view/health">Sport and Health</a></h1>
    		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum orci nec nibh eleifend non tempor enim volutpat. Vestibulum ornare eleifend tellus ut tempor. Suspendisse vel lorem mollis dui ege.</p>
    		</div>
    	</div>	
    	<div class="services">
    		<div class="services_left">
    		<h1><a href="/view/competitions">Community Sports</a></h1>
    		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum orci nec nibh eleifend non tempor enim volutpat. Vestibulum ornare eleifend tellus ut tempor. Suspendisse vel lorem mollis dui ege.</p>
    		</div>
    		<div class="services_left_image">
    		<a href="/view/competitions"><img src="/images/SERVICES_COMMUNITY.png" alt="for schools" /></a>
    		</div>
    	</div>
    	<div class="services">
    		<div class="services_right_image">
    		<a href="/view/training"><img src="/images/SERVICES_TRAINING.png" alt="sport and health" /></a>
    		</div>
    		<div class="services_right">
    		<h1><a href="/view/training">Training and Qualifications</a></h1>
    		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum orci nec nibh eleifend non tempor enim volutpat. Vestibulum ornare eleifend tellus ut tempor. Suspendisse vel lorem mollis dui ege.</p>
    		</div>
    	</div>
    </div>
</div>

<div id="footer_wrapper">
	<p>This is where the address will go along with any other links that need to appear in the footer<br />
Website produced by <a href="http://www.sugarcaneweb.co.uk">www.sugarcaneweb.co.uk</a></p>
</div>

</div>

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>